Project03/django_project/djangologin/djangologin/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from loginapp import views
from gameBoardApp import dispviews

urlpatterns = [
    path('e/daiy29/admin/', admin.site.urls),
    url(r'^e/daiy29/$',views.index,name='index'),
    url(r'^e/daiy29/special/',views.special,name='special'),
    url(r'^e/daiy29/loginapp/',include('loginapp.urls')),
    url(r'^e/daiy29/logout/$', views.user_logout, name='logout'),
    url(r'^e/daiy29/playgame/$', dispviews.createpost, name='createpost'),
    url(r'^e/daiy29/scoreboard/$', dispviews.showboard, name='showboard'), 
]

Project03/django_project/djangologin/loginapp/urls.py
# loginapp/urls.py
from django.conf.urls import url
from loginapp import views
# SET THE NAMESPACE!
app_name = 'loginapp'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'), #registration page
    url(r'^user_login/$',views.user_login,name='user_login'), #login page
]

Project03/django_project/djangologin/gameBoardApp/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title= models.CharField(max_length=300)
    content= models.TextField()
#  This is a model containing the database of usernames and scores for use in the scoreboard

Project03/django_project/djangologin/loginapp/models.py
# loginapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE) #Delete everything that references it if this referenced object is deleted. A one-to-one relationship. 
                                                                   
def __str__(self):
	return self.user.username

Project03/django_project/djangologin/loginapp/forms.py
# loginapp/forms.py
from django import forms
from loginapp.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password')
#class UserProfileInfoForm(forms.ModelForm):
 #    class Meta():
  #       model = UserProfileInfo
   #      fields = ('portfolio_site','profile_pic')

Project03/django_project/djangologin/loginapp/views.py
# loginapp/views.py
from django.shortcuts import render
from loginapp.forms import UserForm 
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'loginapp/index.html') #Home
@login_required
def special(request):
    return HttpResponse("You are logged in !") #Notification
@login_required
def user_logout(request): #Log out, redirect to homepage
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request): # POST request to register
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST) 
        if user_form.is_valid():  #If form filled out correctly, (default character requirements)
            user = user_form.save()  #Store info in database and register user
            user.set_password(user.password)
            user.save()
            registered = True
        else:
          print(user_form.errors) 
    else:
        user_form = UserForm()
      
    return render(request,'loginapp/registration.html',
                          {'user_form':user_form,
                           'registered':registered})
def user_login(request): #POST request to log in
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')   #Prompt to check credentials
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index')) #Log in user
            else:
                return HttpResponse("Your account was inactive.")
        else: #Incorrect login prompt
            print("Incorrect Login.")
            print("Attemped username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'loginapp/login.html', {})

Project03/django_project/djangologin/templates/gameBoardApp/playgame.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Type Racing</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
</head>
<div><header class="bg-light text-center p-3 mb-5">
<h1 class="text-dark">Type Racing</h1>
</header></div>
<div>
<div class="container text-center">
<!-- Brief instructions -->
<p>Type The Given Word Within <span id="seconds" class="badge badge-danger">2</span> Seconds:</p>
<h2 id="current" class="strong">hello</h2>
  <br>
<input id="input" class="form-control form-control-lg" type="text" autofocus="" placeholder="Start typing..." />
<h3 id="msg" class="mt-3">&nbsp;</h3>
<br>

<!-- Id for things that will update -->

<h4>Time Left: <span id="time">0</span> &nbsp;&nbsp; Score: <span id="score">0</span> &nbsp;&nbsp; Attempts: <span id="retryscore">1</span> &nbsp;&nbsp; Highscore: <span id="highscore">0</span></h4>
  
  
  
<!-- Instructions -->
<div class="row mt-5">
<div class="col-md-12">
<div class="card card-body bg-light text-dark">
<h5>How To:</h5>
<p>Type the given word or phrase within the alotted time given. Any unused time will carry over the future rounds. There are big difficulty spikes every 10th round, but to compensate for it you will be given bonus time. To restart the game after a game over, type the current word. This will reset the difficulty, as well as your score and start the timer for your next run. By submitting your score your highest overall score as well as your username will be submitted.</p>
</div>
</div>
</div>
<br><br>

<form name="myform" action="" method="POST" onsubmit="DoSubmit();">
{% csrf_token %}
<!-- Invisible submissions-->
<input type="hidden" value={{ user.username }} name="title"/>
<input type="hidden" name="content" value="0" />
<button type="submit" name="submit" class="btn btn-danger btn-lg btn-block">Submit Score!</button>
</form>
  </div>
  </div>



<script>
// variable declaration 

window.onload = init;
var input = document.querySelector('#input');
var current = document.querySelector('#current');
var score = document.querySelector('#score');
var countDown = document.querySelector('#time');
var msg = document.querySelector('#msg');
var seconds = document.querySelector('#seconds');
var retryscore = document.querySelector('#retryscore');
var highscore = document.querySelector('#highscore');
var time = 2;
var bonusTime = 1;
var points = 0;
var inGame = 1;
var retries = 1;
var hiscore = 0;

//pre-generated list of words

var list1 = [ 
'Cat',
'Doug',
'Easy',
'Pig',
'Dog',
'Fur',
'Song',
'Car',
'Math',
'Park',
'In',
'The',
'Elm'
];
var list2 = [
'Curtis',
'Computer',
'Science',
'Slack',
'Django',
'Javascript',
'HTML',
'Ubuntu',
'Secure',
'Encrypt',
'Bash',
'Script'
];
var list3 = [
'Maximizing',
'Kolkhoznik',
'Kibbutznik',
'Jarovizing',
'Japanizing',
'Jackknives',
'Jackknifed',
'Embezzlers',
'Crackajack'
];
var list4 = [
'CaPiTaL',
'1337 SP3AK',
'xDDDD',
'cd CS1XA3',
'git add -A',
'git push origin master',
'Pizza!',
'0wo',
'Toilet Paper'
];
var list5 = [
'This is literally impossible',
'You can not keep up',
'200 words per min btw',
'learned to type from maplestory',
'learned to type from runescape',
'The quick brown fox jumps over the lazy dog',
'The quick fox brown jumps over the dog lazy',
'I thnik theres a typo here',
];
var list6 = [
'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
'sed do eiusmod tempor incididunt ut labore',
'et dolore magna aliqua. Ut enim ad minim',
'veniam, quis nostrud exercitation ullamco laboris',
'nisi ut aliquip ex ea commodo consequat.',
'Duis aute irure dolor in reprehenderit in voluptate',
'velit esse cillum dolore eu fugiat nulla pariatur.',
'Excepteur sint occaecat cupidatat non proident,',
'sunt in culpa qui officia deserunt mollit anim id est laborum.'
];
var currentList = list1;


function init()
{
  seconds.innerHTML = bonusTime;
  showList(currentList);
  input.addEventListener('input', play);
  setInterval(timer, 1000);
  setInterval(play, 100);

// updates the time that you have on this level, displays current word, and starts. The timer ticks every 1000 ms = 1 second, and a win condition is checked ever 0.1s

}
function play()
{
	if(inGame == 1) //if user has not lost, check if they win, update their points, and adjust difficulty accordingly.
	{
		checkWin();
		score.innerHTML = points;
		diffAdjust();
	}
	else{
		checkHiScore(); //otherwise, check for a highscore, update highscore, then reset and update retries if the current word is entered. Reset variables
            highscore.innerHTML = hiscore;
		reset();
		if (input.value === current.innerHTML){
			retries++;
		    retryscore.innerHTML = retries;
			inGame = 1;
			time = 2;
		}
	}
}
function showList(wordList) //display words
{
	var item = Math.floor(Math.random()*wordList.length); //choose random index in list of words
	current.innerHTML = wordList[item]; //display word
}
function reset() //reset variables
{
	bonusTime = 1;
	points = 0;
	currentList = list1;
	msg.innerHTML = 'Game Over';
}
function diffAdjust() //adjust difficulty. Check point value to update list of words
{
	if(points >= 10 && points < 20){
		currentList = list2;
	}
	else if (points >= 20 && points < 30){
		currentList = list3;
		bonusTime = 2;
	}
	else if (points >= 30 && points < 40){
		currentList = list4;
		bonusTime = 2;
	}
	else if (points >= 40 && points < 60){
		currentList = list5;
		bonusTime = 3;
	}
	else if (points >= 60){
		currentList = list6;
		bonusTime = 4;
	}	
}
function updateMessage(){ // when difficulty is increased / wordlist is updated, update message.
		if ((points == 10) || (points == 20) || (points == 30) || (points == 40) || (points == 60))
		{
			msg.innerHTML = 'Difficulty increased!';
		}
		else{ //display random message for correct input. 
			var rngmsg = Math.floor(Math.random()*3);
				if (rngmsg == 1)
			msg.innerHTML = 'Noice';
			    else if (rngmsg == 2)
			msg.innerHTML = 'EZ4NCE';
		        else
		    msg.innerHTML = 'Gottem';
		}
}
function timer()
{
	if (time > 0 && inGame == 1){ //if still in game, have time decrease by 1 every second
		time--;
	}
	else if (time == 0){ //if time is at 0, end the game. The user has lost
		inGame = 0;
	}
	countDown.innerHTML = time; //update time
}
function checkWin() 
{
	if (input.value === current.innerHTML) { //check if inputted word matches word in list
		points++; //add points, add time, reset input value, update word list, update display of time and message
		time += bonusTime;
		input.value = '';
		showList(currentList);
		seconds.innerHTML = bonusTime;
		updateMessage();
	}
}
function checkHiScore()
{
	if (points > hiscore){ //update high score if this runs score is greater than overall highscore
		hiscore = points;
	}
}
function DoSubmit(){ //submit score
	document.myform.content.value = hiscore;
}
</script>
</html>

Project03/django_project/djangologin/templates/gameBoardApp/scoreboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Leaderboard</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
</head>
<!-- Make a scoreboard with headers Alias, and Score. Go through every entry in ordered database, and print title (name) and content (score) -->
<div><header class="bg-light text-center p-3 mb-5">
<h1 class="text-dark">Leaderboard</h1>
</header></div>

  <table class="table text-center">
    <tr>
      <th scope="col"> Alias </th>
      <th scope="col"> Score </th>
    </tr>
    {% for row in allrows%}
    <tr>
	<td>{{ row.title }}</td>
        <td>{{ row.content }}</td>
    </tr>
    {% endfor %}
</table>
</html>

Project03/django_project/djangologin/templates/loginapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top"> <!-- Navigation bar in container to size-->
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li> <!-- Each links to their respective urls -->
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin Login</a></li>
          <li><a class="navbar-link" href="{% url 'loginapp:register' %}">Register</a></li>     
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'loginapp:user_login' %}">Login</a></li>
          {% endif %}
          {% if user.is_authenticated %}
            <li><a href="{% url 'createpost' %}">Play Game</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'loginapp:user_login' %}">Log in to Play</a></li>
	  {% endif %}
            <li><a class="navbar-link" href="{% url 'showboard' %}">View Recent Scores</a></li>
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

Project03/django_project/djangologin/templates/loginapp/index.html
{% extends "loginapp/base.html" %} <!-- "Added on" to navigation bar -->
{% block body_block %}
<!-- Home page, with a background. Displays message to either log in, or displays welcome message -->
<body style="background-image: url(https://i.imgur.com/hXm7PaF.png); background-repeat: no-repeat; background-size: cover;">
    {% if user.is_authenticated %}
  <h1 style="color:white; font-family:Helvetica; font-size:600%; font-weight:900; position: absolute; left: 0; top: 30%; width: 100%; text-align: center;">Welcome to my website {{ user.username }} !<br> You can nagivate using the navigation bar. </h1>
    {% else %}
  <h1 style="color:white; font-family:Helvetica; font-size:600%; font-weight:900; position:absolute; left:0; top:30%; width: 100%; text-align: center;">Please log in using the nagivation bar.</h1>
    {% endif %}
</body>
{% endblock %}

Project03/django_project/djangologin/templates/loginapp/login.html
    
{% extends 'loginapp/base.html' %} <!-- Extended from nav bar -->
{% block body_block %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}
<!-- CSS for registration form. Visuals can be modified here by changing values --> 

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=password], select, textarea {
  width: 100%;
  padding: 12px;
  border: 3px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container2 {
  border-radius: 5px;
  background-color: transparent;
  padding: 80px;
}
</style>
</head>
<body style="background-image: url(https://i.imgur.com/hXm7PaF.png); background-repeat: no-repeat; background-size: cover;">

<br><br>
<center>
<h1 style="color:white; font-size:300%;"> Log In Here </h1>
</center>
<!-- Makes post request to login -->
<div class="container2">
  <form method="post" action="{% url 'loginapp:user_login' %}">
    {% csrf_token %}
    <label for="username" style="color:white; font-size:150%;">Username:</label>
    <input type="text" name="username" placeholder="Username" style="font-size:150%">

    <label for="password" style="color:white; font-size:150%;">Password:</label>
    <input type="password" name="password" placeholder="Password" style="font-size:150%">

  
    <input type="submit" value="Log In" class="btn btn-lg btn-block">
  </form>
</div>

</body>
</html>

{% endblock %}

Project03/django_project/djangologin/templates/loginapp/registration.html
<!-- Extended from navbar -->    
{% extends 'loginapp/base.html' %}
{% load staticfiles %}
{% block body_block %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
<!-- CSS for page's registration form. Modify values to change visual of form -->
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}
input[type=password], select, textarea {
  width: 100%;
  padding: 12px;
  border: 3px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}
input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
input[type=submit]:hover {
  background-color: #45a049;
}
.container2 {
  border-radius: 5px;
  background-color: transparent;
  padding: 80px;
}
</style>
</head>
<body style="background-image: url(https://i.imgur.com/hXm7PaF.png); background-repeat: no-repeat; background-size: cover;">

<br><br>
<center>
<h1 style="color: white; font-size: 300%;">Register Here</h1>
</center>
<div class="container2" style="font-size: 150%; color:red;">
      {% if registered %} 
      {% elif user.is_authenticated %}
        <center>
        <h1 style="color: white">Thank you for registering!</h1>
        </center>
      {% else %}
<!-- Post request to register w/ userform -->
          <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <input type="submit" name="" value="Register" class="btn btn-lg btn-block">
        </form>
{% endif %}
</div>
{% endblock %}

</body>
</html>